<?php

namespace Database\Seeders;

use App\Models\Umkm;
use App\Models\KategoriUmkm;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class UmkmSeeder extends Seeder
{
    public function run(): void
    {
        // Create sample UMKM data for testing
        $umkmData = [
            [
                'kategori_id' => 1,
                'nama' => 'Warung Makan Pak Budi',
                'slug' => Str::slug('Warung Makan Pak Budi'),
                'deskripsi' => 'Warung makan tradisional dengan menu khas daerah',
                'pemilik' => 'Budi Santoso',
                'alamat' => 'Jl. Raya Desa No. 123',
                'dusun' => 'Dusun 1',
                'rt' => '001',
                'rw' => '001',
                'kecamatan' => 'Kecamatan ABC',
                'kota' => 'Kabupaten XYZ',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '12345',
                'telepon' => '081234567890',
                'whatsapp' => '081234567890',
                'email' => 'warungpakbudi@gmail.com',
                'jenis_usaha' => 'kuliner',
                'status_usaha' => 'aktif',
                'omset_per_bulan' => 15000000,
                'skala_usaha' => 'mikro',
                'jumlah_karyawan' => 3,
            ],
            [
                'kategori_id' => 2,
                'nama' => 'Toko Kelontong Ibu Siti',
                'slug' => Str::slug('Toko Kelontong Ibu Siti'),
                'deskripsi' => 'Toko kelontong lengkap untuk kebutuhan sehari-hari',
                'pemilik' => 'Siti Aminah',
                'alamat' => 'Jl. Mawar No. 45',
                'dusun' => 'Dusun 2',
                'rt' => '002',
                'rw' => '001',
                'kecamatan' => 'Kecamatan ABC',
                'kota' => 'Kabupaten XYZ',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '12345',
                'telepon' => '081234567891',
                'whatsapp' => '081234567891',
                'email' => 'tokositi@gmail.com',
                'sosial_instagram' => '@tokositi',
                'jenis_usaha' => 'perdagangan',
                'status_usaha' => 'aktif',
                'omset_per_bulan' => 8000000,
                'skala_usaha' => 'mikro',
                'jumlah_karyawan' => 2,
            ],
            [
                'kategori_id' => 3,
                'nama' => 'Bengkel Motor Jaya',
                'slug' => Str::slug('Bengkel Motor Jaya'),
                'deskripsi' => 'Bengkel motor dan service kendaraan bermotor',
                'pemilik' => 'Joko Widodo',
                'alamat' => 'Jl. Kendaraan No. 78',
                'dusun' => 'Dusun 3',
                'rt' => '003',
                'rw' => '002',
                'kecamatan' => 'Kecamatan ABC',
                'kota' => 'Kabupaten XYZ',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '12345',
                'telepon' => '081234567892',
                'whatsapp' => '081234567892',
                'jenis_usaha' => 'jasa',
                'status_usaha' => 'aktif',
                'omset_per_bulan' => 12000000,
                'skala_usaha' => 'mikro',
                'jumlah_karyawan' => 4,
            ],
            [
                'kategori_id' => 1,
                'nama' => 'Catering Rumahan',
                'slug' => Str::slug('Catering Rumahan'),
                'deskripsi' => 'Jasa catering untuk acara-acara spesial',
                'pemilik' => 'Ani Wijaya',
                'alamat' => 'Jl. Melati No. 12',
                'dusun' => 'Dusun 1',
                'rt' => '004',
                'rw' => '001',
                'kecamatan' => 'Kecamatan ABC',
                'kota' => 'Kabupaten XYZ',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '12345',
                'telepon' => '081234567893',
                'whatsapp' => '081234567893',
                'email' => 'cateringani@gmail.com',
                'sosial_facebook' => 'Catering Ani',
                'sosial_instagram' => '@catering_ani',
                'jenis_usaha' => 'kuliner',
                'status_usaha' => 'aktif',
                'omset_per_bulan' => 20000000,
                'skala_usaha' => 'kecil',
                'jumlah_karyawan' => 5,
            ],
            [
                'kategori_id' => 4,
                'nama' => 'Tani Organik Sejahtera',
                'slug' => Str::slug('Tani Organik Sejahtera'),
                'deskripsi' => 'Usaha pertanian organik dan penjualan hasil tani',
                'pemilik' => 'Tono Sukarno',
                'alamat' => 'Jl. Sawah Raya No. 99',
                'dusun' => 'Dusun 4',
                'rt' => '001',
                'rw' => '003',
                'kecamatan' => 'Kecamatan ABC',
                'kota' => 'Kabupaten XYZ',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '12345',
                'telepon' => '081234567894',
                'whatsapp' => '081234567894',
                'email' => 'taniorganik@gmail.com',
                'website' => 'www.taniorganik.com',
                'jenis_usaha' => 'pertanian',
                'status_usaha' => 'aktif',
                'omset_per_bulan' => 25000000,
                'skala_usaha' => 'kecil',
                'jumlah_karyawan' => 8,
            ],
            [
                'kategori_id' => 5,
                'nama' => 'Fashion Hijab Modern',
                'slug' => Str::slug('Fashion Hijab Modern'),
                'deskripsi' => 'Toko hijab dan busana muslim modern',
                'pemilik' => 'Fatimah Zahra',
                'alamat' => 'Jl. Fashion No. 33',
                'dusun' => 'Dusun 2',
                'rt' => '005',
                'rw' => '002',
                'kecamatan' => 'Kecamatan ABC',
                'kota' => 'Kabupaten XYZ',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '12345',
                'telepon' => '081234567895',
                'whatsapp' => '081234567895',
                'email' => 'hijabmodern@gmail.com',
                'sosial_instagram' => '@hijab_modern',
                'sosial_tiktok' => '@hijabmodern',
                'shopee_url' => 'shopee.co.id/hijabmodern',
                'tokopedia_url' => 'tokopedia.com/hijabmodern',
                'jenis_usaha' => 'fashion',
                'status_usaha' => 'aktif',
                'omset_per_bulan' => 18000000,
                'skala_usaha' => 'kecil',
                'jumlah_karyawan' => 6,
            ],
            [
                'kategori_id' => 2,
                'nama' => 'Toko Bangunan Maju',
                'slug' => Str::slug('Toko Bangunan Maju'),
                'deskripsi' => 'Penjualan material bangunan dan alat konstruksi',
                'pemilik' => 'Rahman Hakim',
                'alamat' => 'Jl. Konstruksi No. 88',
                'dusun' => 'Dusun 3',
                'rt' => '002',
                'rw' => '003',
                'kecamatan' => 'Kecamatan ABC',
                'kota' => 'Kabupaten XYZ',
                'provinsi' => 'Jawa Tengah',
                'kode_pos' => '12345',
                'telepon' => '081234567896',
                'whatsapp' => '081234567896',
                'email' => 'tokobangunan@gmail.com',
                'jenis_usaha' => 'perdagangan',
                'status_usaha' => 'tidak_aktif',
                'omset_per_bulan' => 35000000,
                'skala_usaha' => 'menengah',
                'jumlah_karyawan' => 12,
            ],
        ];

        foreach ($umkmData as $data) {
            Umkm::create($data);
        }
    }
}
